# Copyright (c) 2015 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

description: Apps and Engines when launching with a project only context.

#################################################################################################
# include common files

includes:
# launchers for launching DCCs such as Maya, Nuke etc.
- ./includes/app_launchers.yml
# common app configurations that are reused across environments
- ./includes/common_apps.yml
- ./includes/pi_apps.yml
# engine_defaults configurations that are reused across environments
- ./includes/engine_defaults.yml


#################################################################################################
# define all the items that should appear in this environment



engines:
  #
  # -------------------------------------------------
  # 3dsmax
  # -------------------------------------------------
  tk-3dsmax:
    apps:
      tk-multi-about: '@about'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
    debug_logging: false
    location:
      version: v0.3.9
      type: app_store
      name: tk-3dsmax
  #
  # -------------------------------------------------
  # 3dsmax plus
  # -------------------------------------------------
  tk-3dsmaxplus:
    apps:
      tk-multi-about: '@about'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
    compatibility_dialog_min_version: 2017
    debug_logging: false
    location:
      version: v0.1.16
      type: app_store
      name: tk-3dsmaxplus
    menu_favourites: []
  #
  # -------------------------------------------------
  # Shotgun Desktop
  # -------------------------------------------------
  tk-desktop:
    apps:
      tk-multi-launchmaya: '@launch_maya'
      tk-multi-launchnuke10.5v2: '@launch_nuke10.5v2'
      tk-multi-launchnuke10.5v2x: '@launch_nuke10.5v2x'
      tk-multi-launchnuke10.5v3: '@launch_nuke10.5v3'
      tk-multi-launchnuke10.5v3x: '@launch_nuke10.5v3x'
      tk-multi-launchpremiere2017: '@launch_premiere2017'
      tk-multi-launchpremiere2015: '@launch_premiere2015' 
      tk-multi-importcut: '@tk-multi-importcut'
      tk-multi-importmedia: '@tk-multi-importmedia'
    collapse_rules:
    - {button_label: $app, match: Launch $app $version, menu_label: $version}
    debug_logging: true
    default_group: Studio
    groups:
    - matches: ['*Houdini*', '*Mari*', '*Max*', '*Maya*', '*Motion*', '*Nuke*', '*Photoshop*',
        '*Softimage*']
      name: Creative Tools
    - matches: ['*Hiero*']
      name: Editorial Tools
    - matches: ['*Fla*']
      name: Finishing Tools
    hook_launch_python: default
    location:
      version: v2.0.10
      type: app_store
      name: tk-desktop
    show_recents: true

  #
  # -------------------------------------------------
  # Houdini
  # -------------------------------------------------
  tk-houdini:
    apps:
      tk-multi-about: '@about'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
    location:
      version: v1.0.7
      type: app_store
      name: tk-houdini
    enable_sg_shelf: true
    debug_logging: false
    enable_sg_menu: true
    menu_favourites: []
  #
  # -------------------------------------------------
  # Mari
  # -------------------------------------------------
  tk-mari:
    apps:
      tk-multi-about: '@about'
      tk-multi-workfiles:
        allow_task_creation: true
        file_extensions: []
        hook_copy_file: default
        hook_filter_publishes: default
        hook_filter_work_files: default
        hook_scene_operation: default
        launch_at_startup: false
        launch_change_work_area_at_startup: false
        location:
          version: v0.7.3
          type: app_store
          name: tk-multi-workfiles
        saveas_default_name: scene
        saveas_prefer_version_up: false
        sg_entity_type_extra_display_fields: {}
        sg_entity_type_filters: {}
        sg_entity_types: [Asset]
        sg_task_filters: []
        task_extra_display_fields: []
        template_publish:
        template_publish_area:
        template_work:
        template_work_area:
        version_compare_ignore_fields: []
    compatibility_dialog_min_version: 2
    debug_logging: false
    location:
      version: v1.1.4
      type: app_store
      name: tk-mari
  #
  # -------------------------------------------------
  # Maya
  # -------------------------------------------------
  tk-maya:
    apps:
      tk-multi-about: '@about'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2-launch-at-startup'
    compatibility_dialog_min_version: 2015
    debug_logging: false
    location:
      version: v0.5.5
      type: app_store
      name: tk-maya
    menu_favourites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
    template_project:
    use_sgtk_as_menu_name: false

  #
  # -------------------------------------------------
  # Motionbuilder
  # -------------------------------------------------
  tk-motionbuilder:
    apps:
      tk-multi-about: '@about'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
    debug_logging: false
    location:
      version: v0.3.1
      type: app_store
      name: tk-motionbuilder
    menu_favourites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
    template_project:
    use_sgtk_as_menu_name: false

  #
  # -------------------------------------------------
  # Nuke
  # -------------------------------------------------
  tk-nuke: '@tk-nuke-no-context-defaults'

  # -------------------------------------------------
  # NukeX
  # -------------------------------------------------
  tk-nukex: '@tk-nuke-no-context-defaults'
  
  #
  # -------------------------------------------------
  # Photoshop
  # -------------------------------------------------
  tk-photoshop:
    apps:
      tk-multi-about: '@about'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
    debug_logging: false
    location:
      version: v0.3.3
      type: app_store
      name: tk-photoshop
  #
  # -------------------------------------------------
  # Shell Engine (tank command)
  # -------------------------------------------------
  tk-shell:
    apps:
      tk-multi-launch3dsmax: '@launch_3dsmax'
      tk-multi-launchmaya: '@launch_maya'
      tk-multi-launchphotoshop: '@launch_photoshop'
      tk-multi-launchsoftimage: '@launch_softimage'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-launchpremiere: '@launch_premiere2017'
      tk-multi-importcut: '@tk-multi-importcut'
      tk-multi-scriptedapp: '@tk-multi-scriptedapp'
      tk-premiere-jauntvr: '@tk-premiere-jauntvr'
      tk-multi-importmedia: '@tk-multi-importmedia'
    location:
      version: v0.4.1
      type: app_store
      name: tk-shell
  #
  # -------------------------------------------------
  # Softimage
  # -------------------------------------------------
  tk-softimage:
    apps:
      tk-multi-about: '@about'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
    debug_logging: false
    location:
      version: v0.3.2
      type: app_store
      name: tk-softimage
    menu_favourites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
    template_project:
    
###############################################################################
#
# Framework includes.
#
# Frameworks are libraries that are shared between apps and that contain
# common functionality for building UIs and communicating with Shotgun.
# Frameworks are automatically installed when apps are installed and udpated.
#
frameworks:
  tk-framework-adminui_v0.x.x:
    location:
      version: v0.1.5
      type: app_store
      name: tk-framework-adminui
  tk-framework-login_v1.x.x:
    location:
      version: v1.2.2
      type: app_store
      name: tk-framework-login
  tk-framework-softimageqt_v1.0.1:
    location:
      name: tk-framework-softimageqt
      type: app_store
      version: v1.0.1

